pdms/config/routes.rb
Rails.application.routes.draw do

  get 'workflows/set'

  get 'workflows/update'
  
  get 'projects/search'
  

  ActiveAdmin.routes(self) 

  get '/users/sign_out' => 'devise/sessions#destroy'
  get 'admin/' => 'admin#index', as: 'admin'
  devise_for :users
  resources :users
  resources :projects 
  resources :documents, except: [:index, :update] do
  resources :versions, only: [:destroy] do
    member do
      get :diff, to: 'versions#diff'
      patch :rollback, to: 'versions#rollback'
    end
  end
end

  resources :tasks
  
  resources :roles

  resources :document_templates

  get 'projects/:id/member' => 'projects#member', as: :member
  post 'projects/:id/member' => 'projects#member'
  get 'projects/:id/assigntask' => 'projects#assigntaskindex', as: :assigntaskindex
  get 'projects/:id/tasks' => 'projects#tasks', as: :tasklist
  get 'projects/:id/edittask/:taskid' => 'projects#edittask', as: :edittask
  post 'projects/:id/updatetask' => 'projects#updatetask', as: :updatetask
  post 'projects/:id/createtask' => 'projects#createtask', as: :createtask
  get 'projects/:id/member/remove_member' => 'projects#remove_member', as: :remove_member
  post 'projects/:id/respondtask/' => 'projects#respondTask'
  get 'projects/:id/respondtask/' => 'projects#respondTask', as: :respond_task

  get 'projects/status/:id' => 'projects#status'

  get 'projects/:id/documents' => 'documents#index', as: :indexdocument
  get 'documents/new/:proj_id/:doctmpl_id' => 'documents#new', as: :newdocument
  post 'documents/create/:proj_id/:doctmpl_id' => 'documents#create'
  get 'documents/delete/:proj_id/:id' => 'documents#destroy'
  get 'documents/edit/:proj_id/:id/:doctmpl_id' => 'documents#edit', as: :editdocument
  post 'documents/edit/:proj_id/:id/:doctmpl_id' => 'documents#edit'
  patch 'documents/update/:proj_id/:id/:doctmpl_id' => 'documents#update'

  get 'tasks/submit/:proj_id/:id' => 'tasks#submitForApproval'

  get 'templates/workflows/set/:doctmpl_id' => 'workflows#set'
  post 'templates/workflows/update/:doctmpl_id' => 'workflows#update', as: :workflowupdate

    root 'projects#index'

end

pdms/app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :document_template

  has_attached_file :docFile

  has_paper_trail on: [:update]

  def user_name
    user ? user.firstName : ''
  end

end

pdms/app/models/document_history.rb
class DocumentHistory < ActiveRecord::Base
#belongs_to :document_template
end

pdms/app/models/document_template.rb
class DocumentTemplate < ActiveRecord::Base

belongs_to :user
has_many :tasks, dependent: :destroy
has_many :documents, dependent: :destroy
has_many :pmbok_workflows
has_attached_file :template

end

pdms/app/models/pmbok_process.rb
class PmbokProcess < ActiveRecord::Base
  has_many :pmbok_workflows
end

pdms/app/models/pmbok_workflow.rb
class PmbokWorkflow < ActiveRecord::Base
  belongs_to :pmbok_process
  belongs_to :document_template

  def doctype=(value)
    doctype = if value.nil? then nil else value[0].upcase end
    super(doctype)
  end

  validates :pmbok_process, presence: true
  validates :document_template, presence: true
  validates :doctype, length: { maximum: 1 }, inclusion: { in: (%w(I O)) << nil }
end

pdms/app/models/project.rb
class Project < ActiveRecord::Base
has_and_belongs_to_many :users
has_many :documents, dependent: :destroy
has_many :tasks, dependent: :destroy
has_many :project_users, dependent: :destroy
end

pdms/app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
  self.table_name = "projects_users"
  belongs_to :user
  belongs_to :project
end

pdms/app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

pdms/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :document_template
  belongs_to :approver, :class_name => "User", :foreign_key => "approver_id"
  belongs_to :assignee, :class_name => "User", :foreign_key => "assignee_id"
  belongs_to :task_status
end

pdms/app/models/task_status.rb
class TaskStatus < ActiveRecord::Base
  has_many :tasks

  validates :name, presence: true
end

pdms/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_and_belongs_to_many :projects
  has_many :documents
  has_many :project_users
  has_many :document_templates
  has_many :tasks, :class_name => "task", :foreign_key => "approver_id"
  has_many :tasks, :class_name => "task", :foreign_key => "assignee_id"

  def admin?
    self.role_id == 1
  end

  def project_manager?
    self.role_id == 2    
  end

  def self.find_version_author(version)
    find(version.terminator)   
  end
  
end

pdms/app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

pdms/app/helpers/application_helper.rb
module ApplicationHelper
end

pdms/app/helpers/documents_helper.rb
module DocumentsHelper
  def find_version_author_name(version)
    user = User.find_version_author(version) 
    user ? user.firstName : ''
  end
end

pdms/app/helpers/projects_helper.rb
module ProjectsHelper
  def getClassNameByTaskStatus(taskStatus)
    taskStatusName = taskStatus.name.downcase
    className = case 
    when taskStatusName.starts_with?('approved')
      'label-success'
    when taskStatusName.starts_with?('submitted for approval')
      'label-info'
    when taskStatusName.starts_with?('revise')
      'label-danger'
    else
      'label-warning'
    end

    "label #{className}"
  end

end

pdms/app/helpers/roles_helper.rb
module RolesHelper
end

pdms/app/helpers/sessions_helper.rb
module SessionsHelper
end

pdms/app/helpers/tasks_helper.rb
module TasksHelper
    def getClassNameByTaskStatus(taskStatus)
    taskStatusName = taskStatus.name.downcase
    className = case 
    when taskStatusName.starts_with?('approved')
      'label-success'
    when taskStatusName.starts_with?('submitted for approval')
      'label-info'
    when taskStatusName.starts_with?('revise')
      'label-danger'
    else
      'label-warning'
    end

    "label #{className}"
  end
end

pdms/app/helpers/versions_helper.rb
module VersionsHelper
end

pdms/app/helpers/workflows_helper.rb
module WorkflowsHelper
end

pdms/app/views/email_notification/notify_added_member_to_project.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Congratulations!</h1>

    <p><%= "#{@user.firstName} #{@user.lastName}" %>, </p>
    <br/>
    <p>
      We are delighted to inform you that you are added into project "<%= @project.name %>". Yay! 
    </p>
    <p>
      For more information, please visit <a href="<%= url_for(controller: 'projects', action: 'show', only_path: false, id: @project.id) %>">this link</a>.
    </p>

    <br/>
    <p>
      May the odds be ever in your favor, <br/>
      PDMS 
    </p>
  </body>
</html>

pdms/app/views/email_notification/notify_added_member_to_project.text.erb
Congratulations!

<%= "#{@user.firstName} #{@user.lastName}" %>, 

We are delighted to inform you that you are added into project "<%= @project.name %>". Yay! 

For more information, please visit this link: <%= url_for(controller: 'projects', action: 'show', only_path: false, id: @project.id) %>

May the odds be ever in your favor,
PDMS 

pdms/app/views/email_notification/notify_new_task.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>New task!</h1>

    <p><%= "#{@user.firstName} #{@user.lastName}" %>, </p>
    <br/>
    <p>
      We are delighted to inform you that you are assigned to work on a document called "<%= @task.document_template.name %>" for project "<%= @project.name %>".
    </p>
    <p>
      For more information, please visit <a href="<%= url_for(controller: 'tasks', action: 'index', only_path: false) %>">this link</a>.
    </p>

    <br/>
    <p>
      May the odds be ever in your favor, <br/>
      PDMS 
    </p>
  </body>
</html>

pdms/app/views/email_notification/notify_new_task.text.erb
New task!

<%= "#{@user.firstName} #{@user.lastName}" %>, 

We are delighted to inform you that you are assigned to work on a document called "<%= @task.document_template.name %>" for project "<%= @project.name %>".

For more information, please visit this link: <%= url_for(controller: 'tasks', action: 'index', only_path: false) %>


May the odds be ever in your favor, 
PDMS 

pdms/app/views/email_notification/notify_task_review_result.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Review result: <%= if @task.task_status_id == 3 then 'APPROVED' else 'REJECTED' end %>!</h1>

    <p><%= "#{@user.firstName} #{@user.lastName}" %>, </p>
    <br/>
    <p>
      We are delighted to inform you that 
      <% if @task.task_status_id == 3 %>
        the task #<%= @task.id %> you submitted for approval has been approved! Good job!!!
      <% else %>
        the task #<%= @task.id %> you submitted for approval has been request for further revision!
        <br/>
        For reason: <%= simple_format @task.remarks %>

        <br/> <br/>
        Keep calm and revise the document! 
      <% end %>
    </p>

    <br/>
    <p>
      May the odds be ever in your favor, <br/>
      PDMS 
    </p>
  </body>
</html>

pdms/app/views/email_notification/notify_task_review_result.text.erb
Review result: <%= if @task.task_status_id == 3 then 'APPROVED' else 'REJECTED' end %>!

<%= "#{@user.firstName} #{@user.lastName}" %>, 


We are delighted to inform you that 
<% if @task.task_status_id == 3 %>
the task #<%= @task.id %> you submitted for approval has been approved! Good job!!!
<% else %>
the task #<%= @task.id %> you submitted for approval has been request for further revision!


For reason: <%= @task.remarks %>


Keep calm and revise the document! 
<% end %>



May the odds be ever in your favor, 
PDMS 

pdms/app/views/email_notification/notify_task_submitted_for_approval.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>A task to review!</h1>

    <p><%= "#{@pm.firstName} #{@pm.lastName}" %>, </p>
    <br/>
    <p>
      We are delighted to inform you that <%= "#{@task.assignee.firstName} #{@task.assignee.lastName}" %> has submitted task #<%= @task.id %> which belongs to project "<%= @project.name %>" for approval.
    </p>
    <p>
      For more information, please visit <a href="<%= url_for(controller: 'projects', action: 'tasks', only_path: false, id: @project.id) %>">this link</a>.
    </p>

    <br/>
    <p>
      Please have some mercy on this poor soul, <br/>
      PDMS 
    </p>
  </body>
</html>

pdms/app/views/email_notification/notify_task_submitted_for_approval.text.erb
A task to review!

<%= "#{@pm.firstName} #{@pm.lastName}" %>, 

We are delighted to inform you that <%= "#{@task.assignee.firstName} #{@task.assignee.lastName}" %> has submitted task #<%= @task.id %> which belongs to project "<%= @project.name %>" for approval.


For more information, please visit this link: <%= url_for(controller: 'projects', action: 'tasks', only_path: false, id: @project.id) %>


Please have some mercy on this poor soul, <br/>
PDMS 

pdms/app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified JQuery -->
<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

pdms/app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container">
    <p class="text-center">&copy; Copyright 2015 PDMS(Group 2). All Rights Reserved.</p>
  </div>
</nav>

pdms/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand" style="min-height: 40px; padding-left: 50px; background-image: url('/pdms_small.png'); background-repeat: no-repeat;">
        <%= link_to "PDMS", root_path %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? and not current_user.admin? %>
          <li><%= link_to "Project", projects_path %></li>
          <li><%= link_to "Task", tasks_path %></li>
          <li><%= link_to "DocumentTemplete", document_templates_path %></li>
        <% end %>
      </ul>

      <div class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <%= form_tag projects_search_path, :method => 'get' do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search",:id =>"search-form" %>
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
          <% end %>
          </div>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            Welcome <%= current_user.firstName %>!
            <li><%= link_to 'Edit account', edit_user_registration_path %></li>
            <li><%= link_to "Sign-out", users_sign_out_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
        <% if user_signed_in? %>
            <% if current_user.admin? %>
                <li><%= link_to 'Admin', admin_path %></li>
            <% end %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

pdms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDMS</title>
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container-fluid">
  <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
      <% end %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>