pdms/config/routes.rb
Rails.application.routes.draw do

  get 'workflows/set'

  get 'workflows/update'
  
  get 'projects/search'
  

  ActiveAdmin.routes(self) 

  get '/users/sign_out' => 'devise/sessions#destroy'
  get 'admin/' => 'admin#index', as: 'admin'
  devise_for :users
  resources :users
  resources :projects 
  resources :documents, except: [:index, :update] do
  resources :versions, only: [:destroy] do
    member do
      get :diff, to: 'versions#diff'
      patch :rollback, to: 'versions#rollback'
    end
  end
end

  resources :tasks
  
  resources :roles

  resources :document_templates

  get 'projects/:id/member' => 'projects#member', as: :member
  post 'projects/:id/member' => 'projects#member'
  get 'projects/:id/assigntask' => 'projects#assigntaskindex', as: :assigntaskindex
  get 'projects/:id/tasks' => 'projects#tasks', as: :tasklist
  get 'projects/:id/edittask/:taskid' => 'projects#edittask', as: :edittask
  post 'projects/:id/updatetask' => 'projects#updatetask', as: :updatetask
  post 'projects/:id/createtask' => 'projects#createtask', as: :createtask
  get 'projects/:id/member/remove_member' => 'projects#remove_member', as: :remove_member
  post 'projects/:id/respondtask/' => 'projects#respondTask'
  get 'projects/:id/respondtask/' => 'projects#respondTask', as: :respond_task

  get 'projects/status/:id' => 'projects#status'

  get 'projects/:id/documents' => 'documents#index', as: :indexdocument
  get 'documents/new/:proj_id/:doctmpl_id' => 'documents#new', as: :newdocument
  post 'documents/create/:proj_id/:doctmpl_id' => 'documents#create'
  get 'documents/delete/:proj_id/:id' => 'documents#destroy'
  get 'documents/edit/:proj_id/:id/:doctmpl_id' => 'documents#edit', as: :editdocument
  post 'documents/edit/:proj_id/:id/:doctmpl_id' => 'documents#edit'
  patch 'documents/update/:proj_id/:id/:doctmpl_id' => 'documents#update'

  get 'tasks/submit/:proj_id/:id' => 'tasks#submitForApproval'

  get 'templates/workflows/set/:doctmpl_id' => 'workflows#set'
  post 'templates/workflows/update/:doctmpl_id' => 'workflows#update', as: :workflowupdate

    root 'projects#index'

end

pdms/app/models/project.rb
class Project < ActiveRecord::Base
has_and_belongs_to_many :users
has_many :documents, dependent: :destroy
has_many :tasks, dependent: :destroy
has_many :project_users, dependent: :destroy
end

pdms/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :member, :assigntaskindex, :createtask, :tasks, :edittask, :status]
  before_filter :authenticate_user!, :except => [:index]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @users = User.all
    @projects = @projects.paginate(:per_page => 5, :page => params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.update_attribute('pm', current_user.firstName + " " + current_user.lastName)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def assigntaskindex
    @documents = DocumentTemplate.all
    @pm = User.where('"firstName" || \' \' || "lastName" = ?', @project.pm)
    @teammembers = @project.users
  end

  def createtask
    doctmpl_id = params[:doctmpl_id]

    # check for an existing task for this project and this document template that still remains unapproved.
    approvedStatus = TaskStatus.where "name LIKE '%Approved%'"
    existingUnapprovedTasks = Task.where(project_id: @project.id, document_template_id: doctmpl_id).where.not(task_status: approvedStatus)

    if existingUnapprovedTasks.count > 0
      flash[:alert] = "Error: There is already a task for this document template that are still unapproved."
      redirect_to action: :assigntaskindex
    else
      doctmpl = DocumentTemplate.find doctmpl_id

      remark = params[:remark]

      approver_id = params[:approver_id]
      approver = User.find approver_id

      assignee_id = params[:assignee_id]
      assignee = User.find assignee_id

      currentDate = Date.parse(Time.now.to_s)

      task = Task.new
      task.project = @project
      task.assignedOn = currentDate
      task.approver = approver
      task.assignee = assignee
      task.document_template = doctmpl
      task.remarks = remark

      task.save

      EmailNotification.notify_new_task(assignee, task, @project).deliver

      redirect_to action: :tasks
    end
  end

  def tasks
    @tasks = Task.where(project_id: @project.id).order('id DESC, task_status_id ASC')
    @taskStatus = TaskStatus.where id: [3, 4]

    if Rails.env.test?
      @tasks.each do |t| 
        t.approver = FactoryGirl.build :project_manager
        t.assignee = FactoryGirl.build :team_member
      end

      @taskStatus = [FactoryGirl.build(:approved_status), FactoryGirl.build(:revise_status)]
    end
  end

  def edittask
    @task = Task.find params[:taskid]
    @teammembers = @project.users
  end

  def updatetask
    task = Task.find params[:taskid]
    newAssignee = User.find params[:assignee_id]

    task.assignee = newAssignee
    task.save
    redirect_to action: 'tasks'
  end

  def respondTask
    taskId = params[:task_id]
    newTaskStatus = nil

    if Rails.env.test?
      _approved_status = FactoryGirl.build :approved_status
      _revise_status = FactoryGirl.build :revise_status
      if params[:respondedStatusID] == '3'
        newTaskStatus = _approved_status
        newTaskStatus.id = 3
      else
        newTaskStatus = _revise_status
        newTaskStatus.id = 4
      end
    else
      newTaskStatus = TaskStatus.find params[:respondedStatusID]
    end

    remarks = params[:remarks]

    task = Task.find taskId

    if newTaskStatus.id == 3
      task.remarks = ''
      task.task_status = newTaskStatus
      task.save

      EmailNotification.notify_task_review_result(task.assignee, task, task.project).deliver
    elsif newTaskStatus.id == 4
      if not remarks.nil? and remarks.strip.length > 0
        task.remarks = remarks
        task.task_status = newTaskStatus
        task.save

      EmailNotification.notify_task_review_result(task.assignee, task, task.project).deliver
      else
        flash[:alert] = 'Error: remarks cannot be empty if you want to have this task revised.'
      end
    end

    redirect_to action: :tasks
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Get /projects/3/member
  def member

    @project_members = Project.find(params[:id]).users

    # @user = User.new
    @project = Project.find(params[:id])

    if params[:user_id]
      @user = User.find(params[:user_id])
      if @project.users << @user and @project.save
        EmailNotification.notify_added_member_to_project(@user, @project).deliver

        flash[:notice] = 'User was saved.'
      end
    end

    @availableTeamMembers = User.where("role_id=3").where.not(id: (ProjectUser.where(project_id: params[:id]).collect {|_pu| _pu.user_id}))
  end

  def remove_member
    project_member = ProjectUser.where(project_id: params[:id], user_id: params[:userid]).delete_all
    redirect_to :member
  end

  def status
    @processes = PmbokProcess.all.order 'id ASC'

    latestTaskForEachDocumentTemplate = \
    %Q(SELECT MAX(t.id) id, MAX("assignedOn") assignedOn, MAX(project_id) project_id, created_at, 
              MAX(updated_at) updated_at, MAX(approver_id) approver_id, MAX(assignee_id) assignee_id, 
              MAX(remarks) remarks, document_template_id, MAX(task_status_id) task_status_id
       FROM tasks t
       WHERE project_id = ?
       GROUP BY t.project_id, t.document_template_id, t.created_at
       HAVING t.created_at = (SELECT MAX(created_at) 
                              FROM tasks tt 
                              WHERE tt.project_id = t.project_id AND 
                                    tt.document_template_id = t.document_template_id))

    @tasks = Task.find_by_sql [latestTaskForEachDocumentTemplate, @project.id]
    @templates = DocumentTemplate.all
    @tasksByDocumentTemplate = @tasks.group_by { |t| t.document_template_id }
  end

  def search
    @search_word = params[:search]
    @results = Project.where("name ILIKE ? OR description ILIKE?", "%#{@search_word}%",
                                "%#{@search_word}%")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :pm, :startDate, :dueDate, :user_id)
    end
end

pdms/app/helpers/projects_helper.rb
module ProjectsHelper
  def getClassNameByTaskStatus(taskStatus)
    taskStatusName = taskStatus.name.downcase
    className = case 
    when taskStatusName.starts_with?('approved')
      'label-success'
    when taskStatusName.starts_with?('submitted for approval')
      'label-info'
    when taskStatusName.starts_with?('revise')
      'label-danger'
    else
      'label-warning'
    end

    "label #{className}"
  end

end

pdms/app/views/projects/assigntaskindex.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to "Basic Info", project_path %></li>
  <li role="presentation"><%= link_to "Status", action: 'status', id: @project.id %></li>
  <li role="presentation"><%= link_to "Members", member_path(:project_id => @project.id) %></li>
  <li role="presentation"><%= link_to "Documents", controller: 'documents', action: 'index' %></li>
  <% if current_user.project_manager? %>
    <li role="presentation" class="active"><%= link_to "Assign Task", assigntaskindex_path(project_id: @project.id) %></li>
    <li role="presentation"><%= link_to "Tasks", tasklist_path(project_id: @project.id) %></li>
  <% end %>
</ul>

<div class="panel-body">
  <%= form_tag(controller: 'projects', action: 'createtask', method: 'post') do %>
  <div class="form-group">
    <label for="document" class="control-label">Document/Document Template: </label>
    <% documentSelectItems = @documents.map {|doc| [doc.name, doc.id]} %>
    <%= select_tag :doctmpl_id, options_for_select(documentSelectItems), class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="approver" class="control-label">Approver</label>
    <% pmItems = @pm.map {|user| [user.firstName + ' ' + user.lastName, user.id]} %>
    <%= select_tag :approver_id, options_for_select(pmItems), class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="assignee" class="control-label">Assignee</label>
    <% assigneeItems = @teammembers.map {|user| [user.firstName + ' ' + user.lastName, user.id]} %>
    <%= select_tag :assignee_id, options_for_select(assigneeItems), class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= submit_tag "Assign task", class: "btn btn-primary", style: "margin-left: 10px;" %>
  </div>
<% end %>

</div>

pdms/app/views/projects/duplicatedtask.html.erb
<div class="panel-body">
  <div class="row">
    <div class="col-md-12">
      <p class="bg-danger">Error: There is already a task for this document template that are still unapproved.</p>
    </div>
  </div>
</div>

pdms/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

pdms/app/views/projects/member.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to "Basic Info", project_path %></li>
  <li role="presentation"><%= link_to "Status", action: 'status', id: @project.id %></li>
  <li role="presentation" class="active"><%= link_to "Members", member_path %></li>
  <li role="presentation"><%= link_to "Documents", controller: 'documents', action: 'index' %></li>
  <% if current_user.project_manager? %>
    <li role="presentation"><%= link_to "Assign Task", assigntaskindex_path(project_id: @project.id) %></li>
    <li role="presentation"><%= link_to "Tasks", tasklist_path(project_id: @project.id) %></li>
  <% end %>
</ul>

<div class="panel-body">
  <div class="row">
    <div class="col-sm-3">
      <p>
        <strong>Project Manager</strong>
      </p>
      <p>
        <%= @project.pm %>
      </p>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-8" style="padding-left: ">
      <strong>Team <%= @project_members.count > 1 ? 'member'.pluralize : 'member' %></strong>

      <ul class="list-group">
        <% @project_members.each do |member| %>
          <li class="list-group-item">
            <%= "#{member.firstName} #{member.lastName}" %>
            <% if current_user.project_manager? %>
              <span style="float: right; vertical-align: middle;">
                <%= link_to "Remove", { action: 'remove_member', userid: member.id }, class: 'btn btn-danger btn-xs' %>
              </span>
            <% end %>
          </li>
        <% end %>
      </ul>

      <% if current_user.project_manager? %>
        <%= form_tag :controller => "projects", :action => "member"  do %>
          <div class="form-group">
            <%= label :user_id, "Select team member to add:" %>
            <% arr = @availableTeamMembers.map {|user| [user.firstName, user.id]} %>
            <%= select_tag :user_id, options_for_select(arr) %>

            <%= submit_tag "Add", class: "btn btn-primary btn-xs", style: "margin-left: 10px;" %>
          </div>
            
        <% end %>
      <% end %>
      
    </div>
  </div>

  

  <%= link_to 'Back', projects_path %>
</div>

pdms/app/views/projects/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-default">
      <div class="panel-heading">
         <strong><h3 class="panel-title">Create New project (PM only)</h3></strong>
      </div>
      <div class="panel-body">
         <%= render 'form' %>
         <%= link_to 'Back', projects_path, class: "btn btn-link"  %>
       </div>
   </div>
</div>

pdms/app/views/projects/show.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><%= link_to "Basic Info", project_path %></li>
  <li role="presentation"><%= link_to "Status", action: 'status', id: @project.id %></li>
  <li role="presentation"><%= link_to "Members", member_path(:project_id => @project.id) %></li>
  <li role="presentation"><%= link_to "Documents", controller: 'documents', action: 'index' %></li>
  <% if current_user.project_manager? %>
    <li role="presentation"><%= link_to "Assign Task", assigntaskindex_path(project_id: @project.id) %></li>
    <li role="presentation"><%= link_to "Tasks", tasklist_path(project_id: @project.id) %></li>
  <% end %>
</ul>

<div class="panel-body">
<p>
  <strong>Project Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @project.startDate %>
</p>

<p>
  <strong>Due Date:</strong>
  <%= @project.dueDate %>
</p>

<p>
  <strong>Project Manager:</strong>
  <%= @project.pm %>
</p>

<% if current_user.role_id == 2 %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %>
<% end %>

</div>

pdms/app/views/projects/status.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to "Basic Info", project_path %></li>
  <li role="presentation" class="active"><%= link_to "Status", action: 'status', id: @project.id %></li>
  <li role="presentation"><%= link_to "Members", member_path(:project_id => @project.id) %></li>
  <li role="presentation"><%= link_to "Documents", controller: 'documents', action: 'index' %></li>
  <% if current_user.project_manager? %>
    <li role="presentation"><%= link_to "Assign Task", assigntaskindex_path(project_id: @project.id) %></li>
    <li role="presentation"><%= link_to "Tasks", tasklist_path(project_id: @project.id) %></li>
  <% end %>
</ul>

<style type="text/css">
  li.list-group-item a{
    color: #111111;
  }
  li.list-group-item a:hover{
    color: #BBBBBB;
  }

  li.list-group-item:hover{
    background-color: #F9F9FA;
  }

  .status-badge{
    min-width: 20px;
  }
</style>

<script type="text/javascript">
  $(document).ready(function() {
    $('[data-toggle="tooltip"]').tooltip();

    $('a.process-btn').click(function(event) {
      $this = $(this);
      $this.blur();
      $visibleContentOfCurrentRow = $this.closest('li').find('div.content:visible');
      if($visibleContentOfCurrentRow.size() > 0)
      {
        $visibleContentOfCurrentRow.slideUp(200);
        return;
      }

      $('a.process-btn').not(this).each(function(index, el) {
        var $link = $(el);
        $link.closest('li').find('div.content').slideUp(200, function(){
          $this.closest('li').find('div.content').delay(200).slideDown('200');
        });
      });
    });
  });
</script>

<div class="panel-body">
  <div class="row">
    <div class="col-md-12">
      <ul class="list-group">
      <% @processes.each_with_index do |process, index| %>
        <li class="list-group-item" style="min-height: 50px; padding-left: 10px;">
          <a href="#" class="process-btn" id="content_<%= process.id %>">
            <div class="row">
              <div class="col-md-6">
                
                  <div style="width: 50%; float: left;">
                    <%= "#{index+1}. #{process.name}" %>
                  </div>
              </div>

              <div class="col-md-6">
                <% _workflowsInProcess = process.pmbok_workflows.select { |w| not w.doctype.nil? } %>
                <% _totalTemplateCount = _workflowsInProcess.count.to_f %>

                <% _templateIdInProcess = _workflowsInProcess.collect { |w| w.document_template_id } %>
                
                <% _tasksRelevantToProcess = [] %>
                <% _templateIdInProcess.each { |id| if not @tasksByDocumentTemplate[id].nil? then @tasksByDocumentTemplate[id].each { |t| _tasksRelevantToProcess << t } end } %>

                <% _tasksByTaskStatus = _tasksRelevantToProcess.group_by { |t| t.task_status_id } %>

                <% _approvedStatus = TaskStatus.where("name LIKE '%Approved%'").first %>
                <% _approvedTasksPercentage = (if _tasksByTaskStatus[_approvedStatus.id].nil? then 0 else _tasksByTaskStatus[_approvedStatus.id].count end) * 100 / _totalTemplateCount %>

                <% _submittedStatus = TaskStatus.where("name LIKE '%Submitted%'").first %>
                <%  _submttedTasksPercentage = (if _tasksByTaskStatus[_submittedStatus.id].nil? then 0 else _tasksByTaskStatus[_submittedStatus.id].count end) * 100 / _totalTemplateCount %>

                <% _inProgressStatus = TaskStatus.where("name LIKE '%In progress%'").first %>
                <% _inProgressTasksPercentage = (if _tasksByTaskStatus[_inProgressStatus.id].nil? then 0 else _tasksByTaskStatus[_inProgressStatus.id].count end) * 100 / _totalTemplateCount %>

                <% _reviseStatus = TaskStatus.where("name LIKE '%Revise%'").first %>
                <% _reviseTasksPercentage = (if _tasksByTaskStatus[_reviseStatus.id].nil? then 0 else _tasksByTaskStatus[_reviseStatus.id].count end) * 100 / _totalTemplateCount %>

                <div class="progress">
                  <div class="progress-bar progress-bar-success" style="width: <%= _approvedTasksPercentage.round %>%" data-toggle="tooltip" data-placement="top" title="Approved">
                  </div>
                  <div class="progress-bar progress-bar-info" style="width: <%= _submttedTasksPercentage.round %>%" data-toggle="tooltip" data-placement="top" title="Submitted for approval">
                  </div>
                  <div class="progress-bar progress-bar-warning" style="width: <%= _inProgressTasksPercentage.round %>%" data-toggle="tooltip" data-placement="top" title="In progress">
                  </div>
                  <div class="progress-bar progress-bar-danger" style="width: <%= _reviseTasksPercentage.round %>%" data-toggle="tooltip" data-placement="top" title="Revise">
                  </div>
                </div>
              </div>
            </div>
          </a>

          <div class="row">
            <div class="col-md-6">
              <div class="content" id="content_<%= index %>" style="display: none;">
                <div class="panel panel-default">
                  <div class="panel-body">
                    <table class="table table-striped table-condensed">
                      <thead>
                        <th>Input</th>
                        <th>Output</th>
                      </thead>
                      <tbody>
                      <% _workflowMap = process.pmbok_workflows.group_by { |w| w.doctype } %>
                      <% _inputWorkflows = if not _workflowMap['I'].nil? then _workflowMap['I'] else [nil] end %>
                      <% _outputWorkflows = _workflowMap['O'] %>
                      <% _inputWorkflows.fill nil, _inputWorkflows.count..._outputWorkflows.count %>
                      <% _rows = _inputWorkflows.zip _outputWorkflows %>
                      <% _rows.each do |row| %>
                        <tr>
                          <td>
                            <% if not row[0].nil? %>
                              <% if not @tasksByDocumentTemplate[row[0].document_template.id].nil? %>
                                <% _task = @tasksByDocumentTemplate[row[0].document_template.id].first %>
                                <p class="<%= getClassNameByTaskStatus(_task.task_status) %> status-badge"><%= _task.task_status.name[0].upcase %></p> 
                              <% end %>
                              <%= row[0].document_template.name %>
                            <% end %>
                          </td>
                          <td>
                            <% if not row[1].nil? %>
                              <% if not @tasksByDocumentTemplate[row[1].document_template.id].nil? %>
                                <% _task = @tasksByDocumentTemplate[row[1].document_template.id].first %>
                                <p class="<%= getClassNameByTaskStatus(_task.task_status) %> status-badge"><%= _task.task_status.name[0].upcase %></p> 
                              <% end %>
                              <%= row[1].document_template.name %>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6"></div>
          </div>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

pdms/app/views/projects/tasks.html.erb
<script type="text/javascript">
  $(document).ready(function(){

    $('.modal#modalRespondTask').appendTo($("body")).find('form').addClass('form form-horizontal');

    $('a.btnRespondTask').click(function(){
      var $this = $(this);

      $('.modal#modalRespondTask').modal();
      if($('select#respondedStatusID').val() == '4')      
      {
        $('div.form-group.remarksGroup').show();
      }
      else
      {
        $('div.form-group.remarksGroup').hide();
      }

      var taskId = $this.closest('tr').find('td.colTaskId').text();
      $('div.modal#modalRespondTask form input[type=hidden][name=task_id]').val(taskId);
    });

    $('select#respondedStatusID').change(function(){
      var $this = $(this);
      if($this.val() == '4')
      {
        $('div.form-group.remarksGroup').slideDown('200');
      }
      else
      {
        $('div.form-group.remarksGroup').slideUp('200');
      }
    });

    $('input#btnSubmitResponse').click(function(){
      if($('select#respondedStatusID').val() == '4')
      {
        if($('textarea#remarks').val().trim().length == 0)
        {
          alert('Please enter remarks!');
          return false;
        }
      }
    });
  });
</script>

<% if Rails.env.test? %>
  <style type="text/css">
  .modal.fade, .fade {
    -webkit-transition: opacity 0.01s;
    -moz-transition: opacity 0.01s;
    -ms-transition: opacity 0.01s;
    -o-transition: opacity 0.01s;
    transition: opacity 0.01s;
  }
  </style>
<%end%>

<p id="notice"><%= notice %></p>

<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to "Basic Info", project_path %></li>
  <li role="presentation"><%= link_to "Status", action: 'status', id: @project.id %></li>
  <li role="presentation"><%= link_to "Members", member_path(:project_id => @project.id) %></li>
  <li role="presentation"><%= link_to "Documents", controller: 'documents', action: 'index' %></li>
  <% if current_user.project_manager? %>
    <li role="presentation"><%= link_to "Assign Task", assigntaskindex_path(project_id: @project.id) %></li>
    <li role="presentation" class="active"><%= link_to "Tasks", tasklist_path(project_id: @project.id) %></li>
  <% end %>
</ul>

<div class="panel-body">
  <div class="col-md-12">
    <table class="table">
      <caption>Task list of project "<%= @project.name %>"</caption>
      <thead>
        <tr>
          <th>Task ID</th>
          <th>Assigned On</th>
          <th>Document</th>
          <th>Approver</th>
          <th>Assignee</th>
          <th>Status</th>
          <th>Commands</th>
        </tr>
      </thead>
      <tbody>
      <% @tasks.each do |task| %>
        <tr id="rowTaskId_<%= task.id %>">
          <td class="colTaskId"><%= task.id %></td>
          <td><%= task.assignedOn %></td>
          <td><%= task.document_template.name %></td>
          <td><%= "#{task.approver.firstName} #{task.approver.lastName}" %></td>
          <td><%= "#{task.assignee.firstName} #{task.assignee.lastName}" %></td>
          <td><p class="<%= getClassNameByTaskStatus task.task_status %>"><%= task.task_status.name %></p></td>
          <td>
            <% if task.task_status_id != 3 %>
              <%= link_to action: 'edittask', id: @project.id, taskid: task.id do %>
              <p class="btn btn-default btn-sm">Edit</p>
              <% end %>
            <% end %>
            <% if task.task_status.name.downcase.ends_with? 'approval' %>
              <a href="#" class="btn btn-warning btn-sm btnRespondTask">Respond</a>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="modal fade" id="modalRespondTask" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="z-index: 9999;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Respond to submitted task</h4>
      </div>
      <%= form_tag action: "respondTask" do %>
      <div class="modal-body">
        <%= hidden_field_tag :task_id %>
        <div class="form-group">
          <div class="col-sm-2" style="height: 100%;">
            <label for="respondedStatusID" class="control-label">Result</label>
          </div>
          <div class="col-sm-10">
            <% taskstatusitems = @taskStatus.map { |status| [status.name, status.id] } %>
            <%= select_tag :respondedStatusID, options_for_select(taskstatusitems), class: 'form-control' %>
          </div>
        </div>
        <div class="form-group remarksGroup">
          <div class="col-sm-2">
            <label for="remarks" class="control-label">Remarks</label>
          </div>
          <div class="col-sm-10">
            <%= text_area_tag :remarks, nil, class: 'form-control', rows: 5 %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Respond", class: "btn btn-primary", id: 'btnSubmitResponse' %>
      </div>
      <% end %>
    </div>
  </div>
</div>