pdms/config/routes.rb
Rails.application.routes.draw do

  get 'workflows/set'

  get 'workflows/update'
  
  get 'projects/search'
  

  ActiveAdmin.routes(self) 

  get '/users/sign_out' => 'devise/sessions#destroy'
  get 'admin/' => 'admin#index', as: 'admin'
  devise_for :users
  resources :users
  resources :projects 
  resources :documents, except: [:index, :update] do
  resources :versions, only: [:destroy] do
    member do
      get :diff, to: 'versions#diff'
      patch :rollback, to: 'versions#rollback'
    end
  end
end

  resources :tasks
  
  resources :roles

  resources :document_templates

  get 'projects/:id/member' => 'projects#member', as: :member
  post 'projects/:id/member' => 'projects#member'
  get 'projects/:id/assigntask' => 'projects#assigntaskindex', as: :assigntaskindex
  get 'projects/:id/tasks' => 'projects#tasks', as: :tasklist
  get 'projects/:id/edittask/:taskid' => 'projects#edittask', as: :edittask
  post 'projects/:id/updatetask' => 'projects#updatetask', as: :updatetask
  post 'projects/:id/createtask' => 'projects#createtask', as: :createtask
  get 'projects/:id/member/remove_member' => 'projects#remove_member', as: :remove_member
  post 'projects/:id/respondtask/' => 'projects#respondTask'
  get 'projects/:id/respondtask/' => 'projects#respondTask', as: :respond_task

  get 'projects/status/:id' => 'projects#status'

  get 'projects/:id/documents' => 'documents#index', as: :indexdocument
  get 'documents/new/:proj_id/:doctmpl_id' => 'documents#new', as: :newdocument
  post 'documents/create/:proj_id/:doctmpl_id' => 'documents#create'
  get 'documents/delete/:proj_id/:id' => 'documents#destroy'
  get 'documents/edit/:proj_id/:id/:doctmpl_id' => 'documents#edit', as: :editdocument
  post 'documents/edit/:proj_id/:id/:doctmpl_id' => 'documents#edit'
  patch 'documents/update/:proj_id/:id/:doctmpl_id' => 'documents#update'

  get 'tasks/submit/:proj_id/:id' => 'tasks#submitForApproval'

  get 'templates/workflows/set/:doctmpl_id' => 'workflows#set'
  post 'templates/workflows/update/:doctmpl_id' => 'workflows#update', as: :workflowupdate

    root 'projects#index'

end

pdms/app/models/document_template.rb
class DocumentTemplate < ActiveRecord::Base

belongs_to :user
has_many :tasks, dependent: :destroy
has_many :documents, dependent: :destroy
has_many :pmbok_workflows
has_attached_file :template

end

pdms/app/controllers/document_templates_controller.rb
class DocumentTemplatesController < ApplicationController
  before_action :set_document_template, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!


  # GET /document_templates
  # GET /document_templates.json
  def index
    @document_templates = DocumentTemplate.all
  end

  # GET /document_templates/1
  # GET /document_templates/1.json
  def show
  end

  # GET /document_templates/new
  def new
    @document_template = DocumentTemplate.new
  end

  # GET /document_templates/1/edit
  def edit
  end

  # POST /document_templates
  # POST /document_templates.json
  def create
    @document_template = DocumentTemplate.new(document_template_params)
    @document_template.update_attribute('uploadedBy', current_user.firstName + " " + current_user.lastName)

    respond_to do |format|
      if @document_template.save
        format.html { redirect_to @document_template, notice: 'Document template was successfully created.' }
        format.json { render :show, status: :created, location: @document_template }
      else
        format.html { render :new }
        format.json { render json: @document_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_templates/1
  # PATCH/PUT /document_templates/1.json
  def update
    respond_to do |format|
      if @document_template.update(document_template_params)
        format.html { redirect_to @document_template, notice: 'Document template was successfully updated.' }
        format.json { render :show, status: :ok, location: @document_template }
      else
        format.html { render :edit }
        format.json { render json: @document_template.errors, status: :unprocessable_entity }
      end
    end
  end

  #Download Template
 # def download
   #send_file(@document_template.template)
  #end

  # DELETE /document_templates/1
  # DELETE /document_templates/1.json
  def destroy
    @document_template.destroy
    respond_to do |format|
      format.html { redirect_to document_templates_url, notice: 'Document template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_template
      @document_template = DocumentTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_template_params
      params.require(:document_template).permit(:name, :template, :uploadedBy, :user_id)
    end
end

pdms/app/helpers/document_templates_helper.rb
module DocumentTemplatesHelper

end

pdms/app/views/document_templates/_form.html.erb
<%= form_for(@document_template) do |f| %>
  <% if @document_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document_template.errors.count, "error") %> prohibited this document_template from being saved:</h2>

      <ul>
      <% @document_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Document Title:' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :template, 'Please select a template document to upload:' %><br>
    <%= f.file_field :template %>
  </div>
  <div class="form-group">
    <%= f.label :uploadedBy, 'Uploaded By:' %><br>
    <%= current_user.firstName + " " + current_user.lastName %>
  </div>
  <div class="actions">
    <%= f.submit "Confirm", :class => "btn btn-primary"%>
  </div>
<% end %>

pdms/app/views/document_templates/_versions.html.erb
<h2>Previous Versions</h2>

<table class='table'>
  <thead>
  <tr>
    <th>Index</th>
    <th>Date</th>
    <th>Author</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <%- document_template.versions.reverse.each do |version| %>
      <tr>
        <td><%= version.index %></td>
        <td><%= version.created_at %></td>
        <td><%= find_version_author_name(version) %></td>
        <td><%= version.event.humanize %></td>
        <td><%= link_to 'Diff', " " %></td>
        <td><%= link_to 'Rollback', rollback_document_template_version_path(document_template, version), method: 'PATCH' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

pdms/app/views/document_templates/edit.html.erb
<h1>Editing Document Template</h1>

<%= render 'form' %>


<%= link_to 'Show', @document_template %> |
<%= link_to 'Back', document_templates_path %>

pdms/app/views/document_templates/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h3>Document Templates</h3></div>
<table class="table">
  <thead>
    <tr>
      <th>Document Title</th>
      <th>Uploaded On</th>
      <th>Uploaded By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @document_templates.each do |document_template| %>
      <tr>
        <td><%= document_template.name %></td>
        <td><%= document_template.created_at.strftime("%-d/%-m/%-Y") %></td>
        <td><%= document_template.uploadedBy %></td>
        <% if current_user && current_user.role_id == 2 %>
        <!-- <td><%= link_to 'Show', document_template %></td> -->
        <td><%= link_to 'Edit', edit_document_template_path(document_template) %></td>
        <td><%= link_to 'Destroy', document_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Set workflow', controller: :workflows, action: :set, doctmpl_id: document_template.id %></td>
        <% end %>
        <td><%= link_to 'Download', DocumentTemplate.find(document_template.id).template.url(:original, false) %>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>


<br>

<% if current_user && current_user.role_id == 2 %>
<div class="col-lg-12 text-right">
  <%= link_to 'New Document template', new_document_template_path, :class => "btn btn-default" %>
</div>
<% end %>

pdms/app/views/document_templates/new.html.erb
<h1>Create Document Templates</h1>

<%= render 'form' %>

<%= link_to 'Back', document_templates_path %>

pdms/app/views/document_templates/show.html.erb
<div class="panel-body">
<p>
  <strong>Name:</strong>
  <%= @document_template.name %>
</p>

<p>
  <strong>Template:</strong>
  <%= @document_template.template_file_name %>
</p>

<%= link_to 'Edit', edit_document_template_path(@document_template) %> |
<%= link_to 'Back', document_templates_path %>
</div>