pdms/config/routes.rb
Rails.application.routes.draw do

  get 'workflows/set'

  get 'workflows/update'
  
  get 'projects/search'
  

  ActiveAdmin.routes(self) 

  get '/users/sign_out' => 'devise/sessions#destroy'
  get 'admin/' => 'admin#index', as: 'admin'
  devise_for :users
  resources :users
  resources :projects 
  resources :documents, except: [:index, :update] do
  resources :versions, only: [:destroy] do
    member do
      get :diff, to: 'versions#diff'
      patch :rollback, to: 'versions#rollback'
    end
  end
end

  resources :tasks
  
  resources :roles

  resources :document_templates

  get 'projects/:id/member' => 'projects#member', as: :member
  post 'projects/:id/member' => 'projects#member'
  get 'projects/:id/assigntask' => 'projects#assigntaskindex', as: :assigntaskindex
  get 'projects/:id/tasks' => 'projects#tasks', as: :tasklist
  get 'projects/:id/edittask/:taskid' => 'projects#edittask', as: :edittask
  post 'projects/:id/updatetask' => 'projects#updatetask', as: :updatetask
  post 'projects/:id/createtask' => 'projects#createtask', as: :createtask
  get 'projects/:id/member/remove_member' => 'projects#remove_member', as: :remove_member
  post 'projects/:id/respondtask/' => 'projects#respondTask'
  get 'projects/:id/respondtask/' => 'projects#respondTask', as: :respond_task

  get 'projects/status/:id' => 'projects#status'

  get 'projects/:id/documents' => 'documents#index', as: :indexdocument
  get 'documents/new/:proj_id/:doctmpl_id' => 'documents#new', as: :newdocument
  post 'documents/create/:proj_id/:doctmpl_id' => 'documents#create'
  get 'documents/delete/:proj_id/:id' => 'documents#destroy'
  get 'documents/edit/:proj_id/:id/:doctmpl_id' => 'documents#edit', as: :editdocument
  post 'documents/edit/:proj_id/:id/:doctmpl_id' => 'documents#edit'
  patch 'documents/update/:proj_id/:id/:doctmpl_id' => 'documents#update'

  get 'tasks/submit/:proj_id/:id' => 'tasks#submitForApproval'

  get 'templates/workflows/set/:doctmpl_id' => 'workflows#set'
  post 'templates/workflows/update/:doctmpl_id' => 'workflows#update', as: :workflowupdate

    root 'projects#index'

end

pdms/app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  belongs_to :document_template

  has_attached_file :docFile

  has_paper_trail on: [:update]

  def user_name
    user ? user.firstName : ''
  end

end

pdms/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @project = Project.find params[:id]
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
    @project = Project.find params[:proj_id]
    @doctmpl = DocumentTemplate.find params[:doctmpl_id]

    @formOptions = {action: :create, proj_id: @project.id, doctmpl_id: @doctmpl.id}
  end

  # GET /documents/1/edit
  def edit
    @project = Project.find params[:proj_id]
    @doctmpl = DocumentTemplate.find params[:doctmpl_id]

    @formOptions = {action: :update, proj_id: params[:proj_id], id: params[:id], doctmpl_id: params[:doctmpl_id]}
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.update_attribute('project_id', params[:proj_id])
    @document.update_attribute('document_template_id', params[:doctmpl_id])
    @document.update_attribute('user_id', current_user.id)

    respond_to do |format|
      if @document.save
        format.html { redirect_to controller: :documents, action: :index, id: params[:proj_id] }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to action: :edit, proj_id: params[:proj_id], id: params[:id], doctmpl_id: params[:doctmpl_id] }
        format.json { render :index, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find params[:id]
    @project = Project.find params[:proj_id]
    @document.destroy
    respond_to do |format|
      format.html { redirect_to controller: :documents, action: :index, id: @project.id, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #Download Template
  #def download
  #send_file(@document.docFile)
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:project_id, :document_template_id, :docFile, :user_id)
    end
end

pdms/app/helpers/documents_helper.rb
module DocumentsHelper
  def find_version_author_name(version)
    user = User.find_version_author(version) 
    user ? user.firstName : ''
  end
end

pdms/app/views/documents/_form.html.erb
<%= form_for @document, url: @formOptions do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= hidden_field_tag :proj_id, @project.id %>
    <%= hidden_field_tag :doctmpl_id, @doctmpl.id %>
    <%= hidden_field_tag :user_id, current_user.id %>
  <div class="field">
    <%= f.label :docFile, "Please upload file:" %><br>
    <%= f.file_field :docFile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pdms/app/views/documents/_versions.html.erb
<h2>Previous Versions</h2>
<table class='table'>
  <thead>
  <tr>
    <th>Index</th>
    <th>Date</th>
    <th>Author</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <%- document.versions.reverse.each do |version| %>
      <tr>
        <td><%= version.index %></td>
        <td><%= version.created_at.strftime("%-d/%-m/%-Y (%I:%M:%P)") %></td>
        <td><%= find_version_author_name(version) %></td>
        <td><%= version.event.humanize %></td>

        <td><%= link_to 'Rollback', rollback_document_version_path(document, version), method: 'PATCH' %></td>
      </tr>
  <% end %>
  </tbody>
</table>

pdms/app/views/documents/edit.html.erb
<%= link_to action: :index, id: @project.id do %>
<p class="btn btn-sm btn-primary">Back to document list</p>
<% end %>

<br>

<h1>Editing document</h1>

<div class="form-group">
  <label for="document" class="control-label">Project: </label>
  <p class="form-control-static"><%= @project.name %></p>
</div>
<div class="form-group">
  <label for="approver" class="control-label">Template Title: </label>
  <p class="form-control-static"><%= @doctmpl.name %></p>
</div>

<%= render 'form' %>

<%= render 'documents/versions', document: @document %>

pdms/app/views/documents/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to "Basic Info", project_path %></li>
  <li role="presentation"><%= link_to "Status", controller: :projects, action: 'status', id: @project.id %></li>
  <li role="presentation"><%= link_to "Members", member_path(:project_id => @project.id) %></li>
  <li role="presentation" class="active"><%= link_to "Documents", controller: 'documents', action: 'index' %></li>
  <% if current_user.project_manager? %>
    <li role="presentation"><%= link_to "Assign Task", assigntaskindex_path(project_id: @project.id) %></li>
    <li role="presentation"><%= link_to "Tasks", tasklist_path(project_id: @project.id) %></li>
  <% end %>
</ul>

<div class="panel-body">

  <h1>Document Lists</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Project</th>
        <th>Document template</th>
        <th>File Name</th>
        <th>Author</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @documents.each do |document| %>
        <tr>
          <td><%= document.project.name %></td>
          <td><%= document.document_template.name %></td>
          <td><%= document.docFile_file_name %></td>
          <td><%= document.user.firstName%>
              <%= document.user.lastName%></td>
          <% if current_user && current_user.role_id == 3 && current_user.firstName == document.user.firstName %>
          <td>
            <%= link_to 'Edit', action: :edit, proj_id: @project.id, id: document.id, doctmpl_id: document.document_template.id %></td>
          <td><%= link_to 'Destroy', action: :destroy, proj_id: @project.id, id: document.id %></td>
          <% end %>
          <% if current_user && current_user.role_id == 2 %>
          <td><%= link_to 'Download', Document.find(document.id).docFile.url(:original, false) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

pdms/app/views/documents/new.html.erb
<%= link_to action: :index, id: @project.id do %>
<p class="btn btn-sm btn-primary">Back to document list</p>
<% end %>

<br>

<h1>Create a document</h1>
    <div class="form-group">
      <label for="document" class="control-label">Project: </label>
      <p class="form-control-static"><%= @project.name %></p>
    </div>
    <div class="form-group">
      <label for="approver" class="control-label">Template Title: </label>
      <p class="form-control-static"><%= @doctmpl.name %></p>
    </div>

<%= render 'form' %>

pdms/app/views/documents/show.html.erb
<p>
  <strong>Project:</strong>
  <%= @document.project.name %>
</p>

<p>
  <strong>Document template:</strong>
  <%= @document.document_template.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @document.user.firstName %>
  <%= @document.user.lastName %>
</p>
  <strong>File:</strong>
  <%= @document.docFile_file_name %>
<p>


</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>